INSERT INTO product (name, cost, created_at) VALUES ('Chocoramo', 2300, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Gansito', 1200, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Mango', 800, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Barrita de chocoramo', 1500, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Quipitos', 700, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Chocolatina', 800, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('BonBonBum', 800, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Gatorade', 300, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Bocadillo', 600, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Barrilete', 300, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Empanada', 1800, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('CocaCola', 2500, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Quatro', 700, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Mani', 1950, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Arroz lb', 2000, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Pasta', 2300, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Atun', 4700, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Yogurt', 2100, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Avena', 2500, NOW());
INSERT INTO product (name, cost, created_at) VALUES ('Gomitas', 2600, NOW());
